name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.0
  - pip=24.2
  - requests=2.32.3
  - scikit-learn=1.5.2
  - pandas=2.2.3
  - pip:
      - mlflow==2.18.0
      - wandb==0.18.7      
